version: '3.8'
services:
  db:
      image: postgres:14.1-alpine
      restart: always
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=eshop-db
      networks:
        - eshopnet
      ports:
          - "5432:5432"
      volumes:
          - db:/var/lib/postgresql/data

  web:
      build:
        dockerfile: Dockerfile
      image: eshop-web
      networks:
        - eshopnet
      ports:
        - "8080:8080"
      depends_on:
        - db
volumes:
    db:
      driver: local

networks:
  eshopnet:
    driver: bridge
